### ISSUE TITLE
ImportError: No module named 'cson'

### ISSUE THREAD

**Issue by avioli** [idleberg/sublime-cson-converter#2]
Cannot install via Package Control, so tried installing manually and I'm getting this in the console:

```
reloading plugin sublime-cson-converter.Converter
Traceback (most recent call last):
  File "/Users/avioli/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 116, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/Users/avioli/Library/Application Support/Sublime Text 3/Packages/sublime-cson-converter/Converter.py", line 2, in <module>
    import cson, dicttoxml, json, xmltodict
ImportError: No module named 'cson'
```

**Comment by idleberg** [comment]
Installing dependencies appears to be unreliable at times. If a restart doesn't fix it, please try running *"Package Control: Satisfy Dependencies"* from the command palette.
